### ISSUE TITLE
ERROR AttributeError: 'Torrent' object has no attribute 'stalled'

### ISSUE THREAD

**Issue by Jorman** [jerrymakesjelly/autoremove-torrents#66] opened 2020-02-28 22:08 UTC
Hi, just upgraded, but I get this error:
```
Fri, 28 Feb 2020 22:46:10 main.py[line:44] INFO Auto Remove Torrents 1.5.0
Fri, 28 Feb 2020 22:46:10 main.py[line:46] INFO Loading configurations...
Fri, 28 Feb 2020 22:46:10 main.py[line:49] INFO Found 1 task(s) in the file.
Fri, 28 Feb 2020 22:46:10 task.py[line:105] INFO Running task 'qBittorrent'...
Fri, 28 Feb 2020 22:46:10 task.py[line:64] INFO Logging in...
Fri, 28 Feb 2020 22:46:10 task.py[line:69] INFO Login successfully. The client is qBittorrent v4.2.1.
Fri, 28 Feb 2020 22:46:10 task.py[line:70] INFO WebUI API version: 2.4 (v2)
Fri, 28 Feb 2020 22:46:10 task.py[line:74] INFO Getting all the torrents...
Fri, 28 Feb 2020 22:46:11 task.py[line:84] INFO Found 42 torrent(s) in the client.
Fri, 28 Feb 2020 22:46:11 strategy.py[line:114] INFO Running strategy Private-Tracker-Torrenting...
Fri, 28 Feb 2020 22:46:11 main.py[line:57] ERROR AttributeError: 'Torrent' object has no attribute 'stalled'
Fri, 28 Feb 2020 22:46:11 main.py[line:58] ERROR Task qBittorrent fails. 
Fri, 28 Feb 2020 22:46:11 main.py[line:59] DEBUG Exception Logged
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/autoremovetorrents/main.py", line 55, in pre_processor
    Task(task_name, result[task_name], not view_mode).execute()
  File "/usr/local/lib/python3.7/dist-packages/autoremovetorrents/task.py", line 108, in execute
    self._apply_strategies()
  File "/usr/local/lib/python3.7/dist-packages/autoremovetorrents/task.py", line 90, in _apply_strategies
    strategy.execute(self._torrents)
  File "/usr/local/lib/python3.7/dist-packages/autoremovetorrents/strategy.py", line 117, in execute
    self._apply_filters()
  File "/usr/local/lib/python3.7/dist-packages/autoremovetorrents/strategy.py", line 70, in _apply_filters
    ).apply(self.remain_list)
  File "/usr/local/lib/python3.7/dist-packages/autoremovetorrents/filter/status.py", line 40, in apply
    if self._acc_stallup and torrent.status == TorrentStatus.Uploading and torrent.stalled:
AttributeError: 'Torrent' object has no attribute 'stalled'
```
I'm using these 2 condition together
```
      last_activity: 129600 # 1,5 days
      status: StalledUpload
```
Is my configuration wrong?

**Comment by jerrymakesjelly** [comment] 2020-02-29 03:24
Sorry it's a bug, I will fix it as soon as possible.

There is no problem in your configurations :)

**Comment by jerrymakesjelly** [comment] 2020-02-29 09:21
@Jorman Would you like to help me check if the problem is solved?

Just clone the ``dev`` branch and install it:

```bash
git clone https://github.com/jerrymakesjelly/autoremove-torrents
cd autoremove-torrents
git checkout dev
python3 setup.py install
```

After that, you can run ``autoremove-torrents`` as usual.

If there is no problem, the ``dev`` branch will be merged into ``master``. When the version 1.5.1 is released, you can uninstall it via ``pip`` and install the official version. :)

**Comment by Jorman** [comment] 2020-02-29 09:54
Seems to work!!! No error reported
Thanks


Il sab 29 feb 2020, 10:21 Zhaoyu Gan <notifications@github.com> ha scritto:

**Closed** 2020-03-01 09:57 UTC
Labels: bug
